apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: monitoring
data:
  filebeat.yml: |
    name: "k8s-filebeat"
    logging.metrics.enabled: false
    xpack.security.enabled: false
    xpack.monitoring.enabled: false
    setup.ilm.enabled: false
    setup.template.enabled: false

    filebeat.inputs:
    - type: container
      enabled: true
      paths:
        - /var/log/containers/*.log
      fields_under_root: true
      json.keys_under_root: true
      json.add_error_key: true
      json.message_key: "log"

    - type: log
      enabled: true
      paths:
        - /var/log/customer-service/*.log
        - /var/log/user-service/*.log
        - /var/log/enrollment-service/*.log
        - /var/log/course-service/*.log
      fields_under_root: true
      json.keys_under_root: true
      json.add_error_key: true
      json.message_key: "message"

    processors:
    - add_kubernetes_metadata:
        host: ${NODE_NAME}
        matchers:
        - logs_path:
            logs_path: "/var/log/containers/"

    output.elasticsearch:
      hosts: ["http://elasticsearch.monitoring.svc.cluster.local:9200"]
      index: "app-logs-%{+yyyy.MM.dd}"

