apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: observability
data:
  logstash.conf: |
    input {
      tcp {
        port => 5000
        codec => "json"
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
      }
      stdout { codec => rubydebug }
    }
