apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: observability
spec:
  ports:
  - port: 9411
    name: zipkin
    targetPort: 9411
  - port: 14250
    name: jaeger-collector-grpc
    targetPort: 14250
  - port: 14268
    name: jaeger-collector-http
    targetPort: 14268
  - port: 14269
    name: jaeger-admin-http
    targetPort: 14269
  - port: 4317
    name: otlp-grpc
    targetPort: 4317
  - port: 4318
    name: otlp-http
    targetPort: 4318
  selector:
    app: jaeger
  type: ClusterIP
