apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: observability
spec:
  ports:
  - port: 4317
    name: grpc
    targetPort: 4317
  - port: 4318
    name: http
    targetPort: 4318
  selector:
    app: otel-collector
