apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer-container
          image: binupaatu/backend-customers:32
          ports:
            - containerPort: 8882
          env:
            - name: MYSQL_HOST
              value: mysql   # MySQL service name within the Kubernetes cluster
            - name: MYSQL_PORT
              value: "3306"  # Default MySQL port
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
