apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  namespace: monitoring   # Optional: Specify the namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer-container
          image: binupaatu/backend-customers:48
          ports:
            - containerPort: 8882
          env:
            - name: MYSQL_HOST
              value: mysql   # MySQL service name within the Kubernetes cluster
            - name: MYSQL_PORT
              value: "3306"  # Default MySQL port
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          volumeMounts:
            - name: logs-volume
              mountPath: /usr/src/app/logs  # This is where Winston writes the logs
      volumes:
        - name: logs-volume
          hostPath:
            path: /var/log/customer-service  # This is where the logs will be stored on the host
            type: DirectoryOrCreate
