apiVersion: v1
kind: Service
metadata:
  name: course-service
spec:
  selector:
    app: course
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8885
      nodePort: 30100
  type: NodePort
